keepass_filename = /Users/michaelmejaeger/Library/CloudStorage/OneDrive-DeutscheBahn/Documents/mimi/dbs.kdbx
#keepass_keyfilename = <path-to-keepass-key-file>
#max_cache_time_in_hours = 10
#use_extra_security_layer = MSG_BOX
#security_layer_timout_in_seconds = 10
#debug = no
# Example configuration file for kp-service
# Options for use_extra_security_layer: NONE, MSG_BOX, TOUCH_ID
